version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: products-db
    environment:
      POSTGRES_USER: xxxx
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: xxxx
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
