spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: admin
    password: admin123

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
