spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/products
    username: admin
    password: admin123

  redis:
    host: redis
    port: 6379

  kafka:
    bootstrap-servers: kafka:9092
